In [1]:
import numpy as np
an_array=np.array([3,33,333])  
print(type(an_array))

<class 'numpy.ndarray'>


In [2]:
an_array2=np.array([[3,33,333],[4,44,444]])
an_array2.shape

(2, 3)

In [3]:
print(an_array[0],an_array[1],an_array[2])

3 33 333


In [4]:
# test the shape of the array we just created, it should have just one dimension 
print(an_array.shape)

(3,)


In [5]:
an_array[0]=888
print(an_array)

[888  33 333]


# How to create a rank 2 numpy array:


In [6]:
another=np.array([[11,12,13],[21,22,33]])
print(another)
print("the shape is 2 row,3 columns:",another.shape)
print("accessing element [0,0],[0,1],and [1,0] of the ndarray:",another[0,0],",",another[0,1],",",another[1,0])

[[11 12 13]
 [21 22 33]]
the shape is 2 row,3 columns: (2, 3)
accessing element [0,0],[0,1],and [1,0] of the ndarray: 11 , 12 , 21


# there are many way to create numpy arrays:

In [7]:
import numpy as np
# create a 2x2 array of zero
ex1=np.zeros((2,2))
print(ex1)

[[0. 0.]
 [0. 0.]]


In [8]:
# create a 2x2 array filled with 9.0
ex2=np.full((3,3),9.0)
print(ex2)

[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]


In [9]:
# create a 2x2 matrix with the diagonal is and the others 0
ex3=np.eye(5,5)
print(ex3 )

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [10]:
# create an array of ones
ex4=np.ones((2,2))
print(ex4)

[[1. 1.]
 [1. 1.]]


In [11]:
# notice thet the above ndarray (ex4) is actually rank 2, it is a 2x1
print(ex4.shape)

# which means we need*to use indexes to access an element
print()
print(ex4[0,0])

(2, 2)

1.0


In [12]:
# create an array of random floats between 0 and 1
ex5=np.random.random((2,2))
print(ex5)

[[0.22897538 0.79657082]
 [0.81878976 0.93688076]]


# Array Indexing

In [13]:
import numpy as np
# rank 2 array of shape (3,4)
an_array=np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [14]:
a_slice=an_array[0:2,1:3]
#select 0 and 1 rows, 1 and 2 column
print(a_slice)

[[12 13]
 [22 23]]


In [15]:
print("before:", an_array[0,1])  # inspect the element at 0,
a_slice[0,0]=1000 # a_slice [0,0] is the same piece of data as an_array[0,1]
print("after:", an_array[0,1])
print(an_array)

before: 12
after: 1000
[[  11 1000   13   14]
 [  21   22   23   24]
 [  31   32   33   34]]


#  Use both integer indexing& slice indexing

In [16]:
# create a rank 2 array of shape(3,4)
an_array=np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [17]:
# using both integer indexing & slicing generate an array of lower rank 
row_rank1=an_array[1,:] # rank 1 view
print(row_rank1,row_rank1.shape) # notice only a single []



[21 22 23 24] (4,)


In [18]:
# slicing alone: generates an array of the same rank as the an_array
row_rank2 = an_array[1:2,:]  # rank3 view
print(row_rank2,row_rank2.shape)  # notice the [[]]

[[21 22 23 24]] (1, 4)


In [19]:
# we can do the same thing for columns of an array :
print()
col_rank1=an_array[:,1]
col_rank2=an_array[ :,1:2]
print(col_rank1,col_rank1.shape) # rank1
print()
print(col_rank2,col_rank2.shape) # rank2


[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


# Array Indexing for changing element:

In [20]:
# create a new array
an_array=np.array([[11,12,13],[21,22,33],[31,32,33],[41,42,43]])
print('original array')
print(an_array)

original array
[[11 12 13]
 [21 22 33]
 [31 32 33]
 [41 42 43]]


In [21]:
# create an array of indices
col_indices=np.array([0,1,2,0])
print('\ncol indices picked :', col_indices)
row_indices=np.arange(4) # arange will select 0,1,2,3
print('\nrows indices picked:',row_indices)


col indices picked : [0 1 2 0]

rows indices picked: [0 1 2 3]


In [22]:
# examine the pairing of row_indices and col_indices. these are the element we'll
for i ,j in zip(row_indices,col_indices):
    print(i,",",j)
'''for i in row_indices:
    for j in col_indices:'''

0 , 0
1 , 1
2 , 2
3 , 0


'for i in row_indices:\n    for j in col_indices:'

In [23]:
# select one element from each row 
print('values in the array at those indices:',an_array[row_indices,col_indices])
# an_array [0,0], an_array[1,1],an_array[2,2],an_array[3,3]=an_array[row_indices]

values in the array at those indices: [11 22 33 41]


In [24]:
# change one element from each row using the indices selected 
an_array[row_indices,col_indices]+=100000 # a=a+10 is same as a+=10

print('\nchanged array:')
print(an_array)


changed array:
[[100011     12     13]
 [    21 100022     33]
 [    31     32 100033]
 [100041     42     43]]


# Boolean Indexing

#  Array Indexing for changing element:

In [25]:
# create a 3x2 array
an_array =np.array ([[11,12],[21,22],[31,32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [26]:
# create a filter which will be boolean values for whether each element meets this 
filter= (an_array>15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [27]:
# w can now slelcted just those element whoch meet that criteria
print(an_array[filter]) # values that are greater than 15.


[21 22 31 32]


In [28]:
# for short, we could have just used the approach below without the need for the sep
an_array[an_array>15]

array([21, 22, 31, 32])

In [29]:
an_array[an_array%2==0] +=100 # a+=100 is same as a=a+100
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


# Datatypes and Array Operations

# Datatypes:

In [30]:
ex1=np.array([11,12]) # python the data type
print(ex1.dtype)

int32


In [31]:
ex2=np.array([11.0,12.0])  # python asign the data type
print(ex2.dtype)

float64


In [32]:
ex3=np.array([11,21],dtype=np.int64)  # you can also tell python the data type
print(ex3.dtype)

int64


In [33]:
# you can use this to force floats into integer (using floor function)
ex4=np.array([11.1,12.7],dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 12]


In [34]:
# you can use this to force integer into floats if you anticipate
# the value may change to floats later
ex5=np.array([11,21],dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[11. 21.]


# Arithmetic Array Operation:


In [35]:
import numpy as np
x=np.array([[111,112],[121,122]],dtype=np.int)
y=np.array([[211.1,212.1],[221.1,222.1]],dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


C:\Users\LENOVO\AppData\Local\Temp\ipykernel_9912\699241481.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x=np.array([[111,112],[121,122]],dtype=np.int)


In [36]:
# add
print(x+y) # the plus sign work
print()
print(np.add(x,y))  # so does the numpy function "add"    

[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [37]:
# multiply 
print(x*y)
print()
print(np.multiply(x,y))

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [38]:
# subtract 
print(x-y)
print()
print(np.subtract(x,y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [39]:
# divide
print(x/y)
print()
print(np.divide(x,y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [40]:
# square root 
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [41]:
# expoment (e ** x)
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


# Set Operation:

# Basic Statistical Operation:

In [42]:
# setup a random 2x5 matrix
arr= 10 * np.random.randn(2,5) # random.random or random.randn or random.randint
print(arr)

[[  4.98805835   9.53418957   4.01906148  -3.45220186  -9.9583569 ]
 [-17.57735258  -4.55666018   8.61678583  12.87394155  -9.08852839]]


In [43]:
# compute the mean for all element 
print(arr.mean())

-0.46010631262863344


In [44]:
# compute the mean by row 
print(arr.mean(axis=1))

[ 1.02615013 -1.94636276]


In [45]:
# compute the mean by row
print(arr.mean(axis=0))

[-6.29464712  2.4887647   6.31792365  4.71086985 -9.52344264]


In [46]:
# sum all the element 
print(arr.sum())

-4.601063126286334


In [47]:
# compute the medians 
print(np.median(arr,axis=1))  # by row 1st and 2nd also 

[ 4.01906148 -4.55666018]


# Sorting:

In [48]:
# create a 10 element array of random 
unsorted=np. random.randn(10)

print(unsorted)

[-0.73444658  0.98661969  0.78853598  0.01937322 -0.5590176   0.77053498
  1.20670414 -1.08010122  0.1527476  -0.73096095]


In [49]:
# create copy and sort 
sorted= np.array(unsorted)
sorted.sort()  # it will arrange value in ascending order i.e sorting 


print(sorted)
print()
print(unsorted)

[-1.08010122 -0.73444658 -0.73096095 -0.5590176   0.01937322  0.1527476
  0.77053498  0.78853598  0.98661969  1.20670414]

[-0.73444658  0.98661969  0.78853598  0.01937322 -0.5590176   0.77053498
  1.20670414 -1.08010122  0.1527476  -0.73096095]


In [50]:
# inplace sorting 
unsorted.sort()
print(unsorted)

[-1.08010122 -0.73444658 -0.73096095 -0.5590176   0.01937322  0.1527476
  0.77053498  0.78853598  0.98661969  1.20670414]


# Finding Unique element:


In [51]:
import numpy as np
array = np.array([1,2,1,4,2,1,4,2])
# print(array.unique())
print(np.unique(array))

[1 2 4]


Set Operation with np.array data type:

In [52]:
s1=np.array(['desk','chair','bulb'])
s2=np.array(['lamp','bulb','chair'])
print(s1,s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [54]:
print(np.intersect1d(s1,s2))   # common values between s1 and s2

['bulb' 'chair']


In [55]:
print(np.union1d(s1,s2))  # common and uncommon values between s1 and s2

['bulb' 'chair' 'desk' 'lamp']


In [56]:
print(np.setdiff1d(s1,s2))  # element in s1 that are not in s2 

['desk']


In [57]:
print(np.in1d(s1,s2))   # which element of s1 is also in s2

[False  True  True]


# Broadcating:

In [58]:
import numpy as np
  
start=np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [60]:
# create a rank1 ndarray with 3 value 
add_rows= np.array([1,0,1])
print(add_rows)

[1 0 1]


In [62]:
y=start+add_rows  # add to each row of 'start' using broadcasting 
print(y)

[[1. 0. 1.]
 [1. 0. 1.]
 [1. 0. 1.]
 [1. 0. 1.]]


In [63]:
# create an ndarray which is 4x1 to broadcast across columns
add_cols=np.array([[0,1,2,3]])  # print(add_cols)
print(add_cols)
add_cols=add_cols.T   # transpose: convert row into column and vice versa

print(add_cols)

[[0 1 2 3]]
[[0]
 [1]
 [2]
 [3]]


In [64]:
# add to each columns of 'start' using broadcasting 
y=start+add_cols
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [66]:
# this will just broadcast in both dimension 
add_scaler=np.array([1])
print(start+add_scaler)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Example from the slides:

In [68]:
# create our 3x4 matrix
arrA=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrA)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [69]:
# create our 4x1 array 
arrB=[0,1,0,2]
print(arrB)

[0, 1, 0, 2]


In [70]:
# add the two together using broadcasting 
print(arrA+arrB)

[[ 1  3  3  6]
 [ 5  7  7 10]
 [ 9 11 11 14]]


# Binary format:

In [71]:
import numpy as np
x=np.array([23.23,24.24])


In [72]:
np.save('an_array',x)  # save the values in x to an_array

In [74]:
np.load('an_array.npy')

array([23.23, 24.24])

# Text format:

In [76]:
np.savetxt('array.txt',X=x,delimiter=',')

In [79]:
## for windows replace "cat" with "type"
!cat array.txt

'cat' is not recognized as an internal or external command,
operable program or batch file.


In [80]:
np.savetxt('array.txt',X=x,delimiter=',')  # savetxt function will store your file 
np.loadtxt('array.txt',delimiter=',')  # delimeter and sep are some which is seperate


array([23.23, 24.24])

# Additional common ndarray 
Opration

In [81]:
# determine the dot product of two matrices
x2d=np.array([[1,1],[1,1]])
y2d=np.array([[2,2],[2,2]])
print(x2d)
print()
print(y2d)
print()
print(x2d.dot(y2d))
print()
print(np.dot(x2d,y2d))

[[1 1]
 [1 1]]

[[2 2]
 [2 2]]

[[4 4]
 [4 4]]

[[4 4]
 [4 4]]


In [84]:
# determine the inner product of two vectors
a1d=np.array([9,9])
b1d=np.array([10,10])

print(a1d.dot(b1d))

print()

print(np.dot(a1d,b1d))

180

180


In [85]:
# dot produce on an array and vector
print(x2d.dot(a1d))  # ([9,9]) ,([1,1],[1,1])  [1*9 + 1*9,1*9 ] = [18,18]
print()
print(np.dot(x2d,a1d))

[18 18]

[18 18]


# Sum: 

In [86]:
# sum element in the array 
ex1=np.array([[11,12],[21,22]])

print(np.sum(ex1))  # add will members 

66


In [87]:
print(np.sum(ex1 , axis=0))  # columnwise sum

[32 34]


In [88]:
print(np.sum(ex1 , axis=1)) # row wise sum

[23 43]


# Element- wise Functions:

for example, let's compare two array values to get the maximum of each

In [89]:
#  random array 
x= np. random.randn(8)
x

array([-1.05436296,  0.89855193, -0.10233342,  0.40960144,  0.13689652,
       -0.56919979,  0.60704174, -0.67659457])

In [90]:
# another random array 
y=np.random.randn(8)

y

array([-0.06052082, -0.88955962, -0.97427889, -1.96358224,  0.84538903,
       -0.00451379, -0.71571524, -0.40536899])

In [91]:
# return element wise maximum between two arrays 
import numpy as np
x=np.random.randn(2,3)
y=np.random.randn(2,3)
np.maximum(x,y)

array([[0.50450942, 0.62265925, 1.33261567],
       [1.10426828, 0.39809583, 0.4948259 ]])

# Reshaping array:

In [93]:
# grab values from 0 through 19 in an array
arr= np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [94]:
# reshape to be a 4x5 matrix
arr.reshape(4,5)  # 5,4



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# Transpose:

In [96]:
# transpose
ex1 = np.array([[11,12],[21,22]])

ex1.T

array([[11, 21],
       [12, 22]])

# Indexing using where():

In [98]:
x_1=np.array([1,2,3,4,5])

y_1=np.array([11,22,33,44,55])
# where we have true in filter it will print x_1 value and for false y_1 value
# this is the working of where function
filter=np.array([True,False,True,False,True])

In [99]:
out=np.where(filter,x_1,y_1)
print(out)

[ 1 22  3 44  5]


In [100]:
mat=np.random.randn(5,5)
mat

array([[-2.09584864, -1.14771566,  1.24154517,  1.4758066 ,  0.73595136],
       [-1.78298587,  0.26778632, -0.20232429,  0.21999707, -1.33772088],
       [-0.63034087, -0.21868324,  0.43003254,  1.16776586,  0.99746216],
       [-2.78099616,  1.04421962, -0.10568469,  0.12748341, -0.25279322],
       [-2.28558116, -0.4845289 , -0.31083333, -0.99828298, -2.31213678]])

In [101]:
np.where(mat>0.5,1000,-1)

array([[  -1,   -1, 1000, 1000, 1000],
       [  -1,   -1,   -1,   -1,   -1],
       [  -1,   -1,   -1, 1000, 1000],
       [  -1, 1000,   -1,   -1,   -1],
       [  -1,   -1,   -1,   -1,   -1]])

In [102]:
'''
if mat>0.5:
    replace(1000)
else:
    replace(-1)'''

'\nif mat>0.5:\n    replace(1000)\nelse:\n    replace(-1)'

# " any" or "all" conditional:

In [105]:
arr_bools=np.array([True,False,True,True,False])

In [106]:
arr_bools.any() # is any values True

True

In [107]:
arr_bools.all() # are all values True 

False

# Random Number Generation:

In [108]:
import numpy as np
y=np.random.normal(size=(1,5))
print(y)

[[ 0.90250422  0.6302748  -0.18773282 -0.34407589 -1.89739849]]


In [111]:
z=np.random.randint(low=2,high=50,size=4)  # int integer values
print(z)   # low for lower limits and high for higher limits

[16 13 29 13]


In [112]:
np.random.permutation(z)  # return a new ordering of element in z

array([29, 16, 13, 13])

In [113]:
np.random.uniform(size=4) # uniform distribution

array([0.8422847 , 0.53597298, 0.63026877, 0.04530309])

In [114]:
np.random.normal(size=4) #normal distributionsize=4

array([-0.69283578, -1.07517308, -0.74392621,  0.5710742 ])

# Merging data sets:

In [115]:
k = np.random.randint (low=2,high=50,size=(2,2))
print(k)

print()
m=np.random.randint(low=2,high=50,size=(2,2))
print(m)

[[40 26]
 [24 13]]

[[36 31]
 [44  6]]


In [116]:
np.vstack((k,m))  # jion vertivally

array([[40, 26],
       [24, 13],
       [36, 31],
       [44,  6]])

In [117]:
np.hstack((k,m))  # join horizontally

array([[40, 26, 36, 31],
       [24, 13, 44,  6]])

In [118]:
np.concatenate([k,m],axis=1)

array([[40, 26, 36, 31],
       [24, 13, 44,  6]])